routes/web.php
<?php

Route::get('/', 'HomeController@index');
Route::get('admin', 'AdminController@index')->middleware('employee');
Route::get('admin/client-video', 'AdminController@clientVideo')->middleware('employee');
Route::resource('admin/our-community', 'OurCommunitiesController');
Route::post('admin/post-client-video', 'AdminController@post_clientVideo')->middleware('employee');
Route::get('/admin/receive-mail/{id}', 'AdminController@receiveMail')->middleware('auth');
Route::post('admin/video-record', 'VideoController@video')->middleware('employee');
Route::get('admin/progress-report', 'AdminController@progress')->middleware('employee');
Route::get('/admin/progress-report/{user}', 'AdminController@progressReportUser')->middleware('employee');
Route::get('/admin/progress-report/{user_id}/{job_id}', 'AdminController@progressReportUserJob')->middleware('employee');

// messages
Route::get('admin/message', 'MessageController@intro')->middleware('auth');

Route::get('admin/message/{jobid}', 'MessageController@index')->middleware('auth');
Route::post('admin/message-image', 'MessageController@sendImage')->middleware('auth');
Route::get('admin/messages/{jobid?}', 'MessageController@getMessages')->middleware('auth');
Route::post('admin/messages', 'MessageController@postMessage')->middleware('auth');

// users
Route::get('admin/users', 'UserController@index')->middleware('admin');
Route::get('admin/users/{role}', 'UserController@index')->middleware('admin');
Route::post('admin/add-user', 'UserController@addUser')->middleware('admin');
Route::post('admin/delete-user', 'UserController@deleteUser')->middleware('admin');
Route::post('admin/user-history', 'UserController@userHistory')->middleware('admin');
Route::post('admin/user-edit', 'UserController@userEdit')->middleware('admin');
Route::post('user/notification', 'UserController@notification')->middleware('employee');

Route::get('admin/enquiries/{id?}', 'EnquiryController@index')->middleware('employee');
Route::post('admin/enquiries', 'EnquiryController@update')->middleware('employee');
Route::post('admin/enquiries/upload', 'EnquiryController@upload')->middleware('employee');
Route::post('admin/enquiries/delete', 'EnquiryController@delete')->middleware('employee');
Route::post('/admin/enquiries/doc/delete', 'EnquiryController@deleteDoc')->middleware('employee');


// my jobs
Route::get('admin/my-jobs', 'MyJobsController@index')->middleware('employee');
Route::get('/admin/my-jobs/archived', 'MyJobsController@archived')->middleware('employee');
Route::get('admin/my-jobs/sketch-pad/{job_id}', 'MyJobsController@sketchPad')->middleware('employee');

Route::get('/admin/my-jobs/add/{type}', 'MyJobsController@add')->middleware('employee');
Route::get('/admin/my-jobs/view/{jobid}', 'MyJobsController@view')->middleware('employee');
Route::get('/admin/my-jobs/tasks/{job_id}', 'MyJobsController@task')->middleware('employee');
Route::post('/admin/jobs/tasks', 'MyJobsController@addTask')->middleware('employee');
Route::post('admin/jobs/add/partywall/{jobid?}', 'MyJobsController@create')->middleware('employee');


Route::post('/admin/jobs/add/survey/{jobid?}', 'MyJobsController@createSurvey')->middleware('employee');

Route::post('/admin/my-jobs/tasks/delete', 'MyJobsController@deleteTask')->middleware('employee');
Route::post('/admin/my-job/delete-payment', 'MyJobsController@deletePayment')->middleware('employee');
Route::post('/admin/my-job/settled-payment', 'MyJobsController@settlePayment')->middleware('employee');
Route::post('admin/my-jobs/upload', 'MyJobsController@upload')->middleware('employee');
Route::post('admin/my-jobs/archive', 'MyJobsController@archive')->middleware('employee');



Route::post('/admin/job/payment', 'MyJobsController@payment')->middleware('employee');
Route::post('/admin/job/add-payment', 'MyJobsController@addPayment')->middleware('employee');


Route::post('admin/job-history', 'MyJobsController@userHistory')->middleware('employee');

Route::get('/admin/my-jobs/users/{job_id}', 'MyJobsController@users')->middleware('employee');
Route::get('/admin/my-jobs/users/{job_id}/{user_id}', 'MyJobsController@addUser')->middleware('employee');
Route::get('/admin/my-jobs/users/delete/{job_id}/{user_id}', 'MyJobsController@deleteUser')->middleware('employee');

Route::post('admin/my-jobs/delete', 'MyJobsController@deleteJob')->middleware('employee');

// tasks
Route::get('admin/tasks', 'TaskController@index')->middleware('employee');
Route::post('admin/render', 'TaskController@render')->middleware('auth');
Route::get('admin/tasks/{type}', 'TaskController@index')->middleware('employee');
Route::post('admin/add-task', 'TaskController@addTask')->middleware('employee');
Route::post('admin/delete-task', 'TaskController@delTask')->middleware('employee');
Route::post('admin/rename-task', 'TaskController@renameTask')->middleware('employee');
Route::post('admin/send-mail', 'TaskController@sendMail')->middleware('employee');

// storage
Route::get('admin/storage', 'StorageController@index')->middleware('employee');
Route::post('admin/storage', 'StorageController@index')->middleware('employee');
Route::post('admin/storage/upload', 'StorageController@upload')->middleware('employee');

Route::post('admin/storage/server/{action?}', 'StorageController@server')->middleware('employee');
Route::get('admin/storage/server/{action?}', function () { return view('admin.engine-fm.server'); });
Route::post('admin/jobs/surveyor-role','AdminController@surveyorRole')->middleware('employee');
//Route::get('/home', 'HomeController@index');
/*Route::get('admin/storage/server/{action?}', function ($action="") { 

return view('admin.engine-fm.server');
});*/

Route::get('admin/my-jobs/doc/regen',  'ExportController@regen')->middleware('employee');


Route::get('admin/jobs', 'JobsController@jobs')->middleware('employee');
Route::get('admin/jobs/archived', 'JobsController@archived')->middleware('employee');
Route::get('admin/jobs/{job_id}/{type?}', 'JobsController@job')->middleware('employee');
Route::post('/admin/jobs/doc/delete', 'JobsController@delete')->middleware('employee');
Route::post('/admin/upload',  'JobsController@upload')->middleware('auth');

// doc generator
Route::get('admin/my-jobs/doc/{jobid}',  'ExportController@gen')->middleware('employee');
Route::get('admin/my-jobs/surveying/{jobid}',  'ExportController@genSurveying')->middleware('employee');

Route::get('admin/my-jobs/download/{jobid}',  'ExportController@download')->middleware('employee');
Route::get('admin/my-jobs/pdf/{jobid?}',  'ExportController@pdf')->middleware('employee');
Route::get('admin/my-jobs/download-standard-documents/{jobid}',  'ExportController@downloadStandardPdf')->middleware('employee');
Route::get('admin/my-jobs/download-uploaded-documents/{jobid}',  'ExportController@downloadUploadedPdf')->middleware('employee');
Route::post('admin/my-jobs/download-sketchpad/{jobid}',  'ExportController@downloadSketch')->middleware('employee');


Route::post('tasks/checked',  'TaskController@checked')->middleware('auth');

Route::post('admin/my-jobs/doc/delete',  'MyJobsController@deleteDoc')->middleware('auth');
Route::post('admin/my-jobs/doc/transfer',  'MyJobsController@transferDoc')->middleware('auth');
Route::post('admin/my-jobs/doc/download-file',  'MyJobsController@downloadFile')->middleware('auth');
Route::get('admin/my-jobs/doc/download-user-history/{user}',  'MyJobsController@downloadUserHistory')->middleware('auth');
Route::post('admin/my-jobs/doc/download-user-history',  'MyJobsController@selectUserHistory')->middleware('auth');
Route::post('admin/my-jobs/doc/rename-file',  'MyJobsController@rename')->middleware('auth');
Route::post('admin/my-jobs/doc/get-standard-folder',  'MyJobsController@getStandardFolder')->middleware('auth');
Route::post('admin/my-jobs/doc/get-uploaded-folder',  'MyJobsController@getUploadedFolder')->middleware('auth');

Route::post('admin/user-note',  'NoteController@store')->middleware('auth');
Route::post('admin/user-note/update',  'NoteController@update')->middleware('auth');

Route::get('admin/user-note/details/{id}',  'NoteController@edit')->middleware('auth');
Route::get('admin/user-note/history/{id}',  'NoteController@history')->middleware('auth');
Route::delete('admin/user-notes/delete/{note_id}',  'NoteController@destroy')->middleware('auth');


// client
Route::get('meditation', 'AdminController@index')->middleware('auth');
Route::get('client', 'AdminController@index')->middleware('auth');
Route::get('client/message/{jobid?}', 'MessageController@client')->middleware('auth');
Route::get('client/discount/{jobid?}', 'DiscountController@index')->middleware('auth');
Route::post('client/discount-post/{jobid?}', 'DiscountController@dicountPost')->middleware('auth');
Route::get('client/our-community/{jobid?}', 'DiscountController@ourCommunity')->middleware('auth');
Route::get('client/meet-your-surveyor/{jobid?}', 'DiscountController@meetYourSurveyour')->middleware('auth');
Route::get('client/tasks/{jobid?}', 'TaskController@client')->middleware('auth');
Route::get('client/documents/{job_id?}', 'JobsController@job')->middleware('auth');
Route::get('client/documents/{job_id}/{type?}', 'JobsController@job')->middleware('auth');
Route::get('client/payment/{job_no?}', 'MyJobsController@clientPayment')->middleware('auth');
Route::post('client/payment-process', 'MyJobsController@paymentProcess')->middleware('auth');
Route::post('client/message-image', 'MessageController@sendImage')->middleware('auth');
Route::get('client/terms-and-condition', 'AdminController@getTermsCondition')->middleware('auth');


Auth::routes();

// test method
Route::get('test', function(){

	\Illuminate\Support\Facades\Mail::send('emails.test', [  'user' => 'bob',  'msg' => ' msg bob'], function ($message){
            $message->subject('Contact  test Form');
            $message->to('ali@tonbul.com');  
          });
	echo 'sent';
});

Route::get('video-test', function () {
    return view('video');
});

app/Bo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bo extends Model
{
    protected $table='bo';
    
	public function getCreatedAtAttribute($value) {
            return  date('d-m-Y H:i', strtotime($value)); 
    }
    public function getUpdatedAtAttribute($value) {
            return  date('d-m-Y H:i', strtotime($value));   
    }
       public function job()
    {
        return $this->belongsTo(Job::class);
    }
}

resources/views/admin/message.blade.php
@extends('layouts.frame')

@section('content')
<style>
    nav-pills>li.active>a, .nav-pills>li.active>a:focus, .nav-pills>li.active>a:hover {
    color: #fff;
    background-color: #84939e;
}
.nav-pills>li.active>a, .nav-pills>li.active>a:focus, .nav-pills>li.active>a:hover {
    color: #fff;
    background-color: #84939e;
}
#job-search-btn{

    background-color: #fff;
    color: #b3b3b3;
    border: solid 0.5px #b3b3b3;
    border-radius: 5px;
    width: 100%;
    border-radius: 0px;
  }
  .open > .dropdown-menu {
    display: block;
    width: 100%;
    margin-top: 0px;
    border-radius: 0px;
    height: auto;
    max-height: 200px;
    overflow-x: hidden;
}

.list-group{
    max-height: 300px;
    margin-bottom: 10px;
    overflow:scroll;
    -webkit-overflow-scrolling: touch;
}
.list-group-item.active, .list-group-item.active:hover, .list-group-item.active:focus {
    background-color: #41485f;
    border-color: #19baa6;
}
.loder-img {
    width: 100%;
    height: 100%;
    position: fixed;
    top: 0;
    right: 0;
    background: rgb(63, 186, 166,0.5);
    z-index: 123;
}
.loder-img img{
    position: absolute;
    left: 0;
    top: 50%;
    right: 0;
    margin: 0 auto;
    margin-top: -50px;
}
@media (min-width: 1200px){
    .container {
        width: 100% !important;
        max-width: 1170px !important;
        margin: 0 auto !important;
    }
}
</style>
<div id="app">
    <div class="loder-img" style="display: none;"><img src="{{ asset('images/loading.gif') }}" style="height: 100px;"></div>
    <div class="container-fluid">
        <div class="container">
            <div class="row">   
                <div class="col-md-12">
                    <h1>
                        Messaging 
                        <span class="badge" style="font-size: 35px; background-color: #1abaa5; border-radius: 35px;"> 
                            @{{ usersInRoom.length }}
                        </span>
                    </h1>  
                    <p>Please select a job to view messages</p> 
                    <ol class="breadcrumb"> 
                        <li><a href="{{ url('admin') }}">Home</a></li>
                       
                            <li><a href="{{ url('admin/message') }}">Message</a></li>
                       
                        <li class="admin/jobs">  BLSN{{ $job->id }}</li>
                    </ol>
                </div>
                <div class="col-md-4 col-sm-4 hidden-xs">   
                    <input type="text" class="form-control" id="job_no_search" placeholder="serach"><br>
                    <div class="list-group">                        
                        @foreach ($jobs as $j)
                            <a class="list-group-item {{ $j->id ==$job->id ? 'active':'' }}" href="{{ url('/admin/message/'.$j->id) }}">
                                BLSN{{  $j->id }} 
                                <span class="badge">{{  $j->messages->count() }} : messages </span>
                            </a>
                        @endforeach
                    </div>                       
                </div>

                <div class="col-md-8 col-sm-8 col-xs-12">           
                    <chat-log :messages="messages"></chat-log>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid" style="background-color: #414861">
        <div class="container">
            <p class="text-center" style="margin-top: 20px; font-size: 20px; color: #85939f;"><strong>Reply to the conversation here ...</strong></p>
            <chat-composer v-on:messagesent="addMessage"></chat-composer>
        </div>
    </div>
</div>

 <div class="modal fade" id="introModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Intro video</h4>
        </div>
        <div class="modal-body">
            <video width="100%" id="vid" controls>
                <source src="{{ asset('video/intro.mp4') }}" type="video/mp4">
                Your browser does not support HTML5 video.
            </video>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
@endsection
@section('script')

<script src="{{ asset('js/custom.js') }}" ></script>
<script type="text/javascript">
    $(document).ready(function(){
      $("#job_no_search").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $(".list-group a").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });  

        $(document).on('click', '#intro_video', function(event) {
        event.preventDefault();
        jQuery.noConflict();
        $("#introModal").modal('show');

        $("#introModal").on('shown.bs.modal', function () {
            $('#vid').get(0).play();

            
        });
    });
    $(".chat-log").animate({ scrollTop: $('.chat-log').prop("scrollHeight")+3000}, 1000); 
</script>

@endsection

resources/views/admin/messages.blade.php
@extends('layouts.frame')

@section('content')
<style>
    .nav-pills>li>a {
    padding: 20px;
}

#job-search-btn{

    background-color: #fff;
    color: #b3b3b3;
    border: solid 0.5px #b3b3b3;
    border-radius: 5px;
    width: 100%;
        border-radius: 0px;
  }
  .open > .dropdown-menu {
    display: block;
    width: 100%;
    margin-top: 0px;
    border-radius: 0px;
    height: auto;
    max-height: 300px;
    overflow-x: hidden;
    
}

.list-group{
    max-height: 300px;
    margin-bottom: 10px;
    overflow:scroll;
    -webkit-overflow-scrolling: touch;
}
</style>
<div id="app">
    <div class="container-fluid">
        <div class="container" style="min-height: 80vh;">
            <div class="row">   
                 <div class="col-md-12">
                    <h1>Messaging</h1>  
                    <p>Please select a job to view messages</p> 
                     <ol class="breadcrumb"> 
                      <li><a href="{{ url('admin') }}">Home</a></li>
                      <li class="admin/jobs">  Messages</li>
                    </ol>
                </div>
                <div class="col-md-4">
                   <div class="list-group">
                        <input type="text" class="form-control" id="job_no_search" placeholder="serach"><br>
                        @foreach ($jobs as $job)
                            <a class="list-group-item" href="{{ url('/admin/message/'.$job->id) }}">
                                BLSN{{  $job->id }} 
                                <span class="badge">{{  $job->messages->count() }} : messages </span>
                            </a>
                        @endforeach
                    </div>   
                </div>

                <div class="col-md-8">
                    @if ($msgs->count() >=1)           
                        <h2>Messages you missed out on</h2>
                            @foreach($msgs as $msg)
                                <div class="well" style="background: #44b39e; color: #fff; border-radius: 30px;">
                                <p class="lead"> {{ $msg->message }}</p>
     
        <hr>
        <div>  
                @if(Auth::user()->role==9)
                    <a  class="btn btn-default" href="{{ url('/admin/message/'.$msg->job_id) }}">View Full conversation </a>
                @elseif(Auth::user()->role==7)
                    <a  class="btn btn-default btn-xs" href="{{ url('/employee/message/'.$job->id) }}">{{  $job->job_no }} </a>
                             
                @endif   
                    
                    <p class="pull-right">{{ $msg->user->name ?? null}} - {{ $msg->created_at ?? null }}</p></div>
       

                    </div>
                   @endforeach
                   @endif
                    
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid" style="background-color: #414861">
        <div class="container">
            <p class="text-center" style="margin-top: 20px; font-size: 20px; color: #85939f;"><strong> @if (Request::is('admin/message/*')) Reply to the conversation here ... @endif</strong></p>
            <chat-composer v-on:messagesent="addMessage"></chat-composer>
        </div>
    </div>
</div>


@endsection
@section('script')
<script type="text/javascript">
    $(document).ready(function(){
      $("#job_no_search").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $(".list-group a").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });     
</script>
@endsection

resources/views/admin/progress_report.blade.php
@extends('layouts.frame')

@section('content')
<style type="text/css">
    h4{
            font-weight: bold;
    color: #414860;
    }
    h5{
color: #cccccc;
padding-top: 35px;
/*padding-bottom: 20px; */
    }
    h2 {
    color: #00b29c;
    font-weight: bold;
    font-size: 4em;
}
</style>
<div class="container-fluid">
    <div class="container" style="min-height: 80vh;">
         <div class="row">
            <div class="col-md-12">
                <h1>Progress Report</h1>
                <ol class="breadcrumb">
                    <li><a href="{{ url('admin') }}">Admin</a></li>
                    <li>Progress Report</li>
                </ol>
            </div>
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>

                                <th></th>
                                <th> <h4>Name</h4></div>
                                <th> <h4 class="text-center">No of Jobs</h4></th>
                                <th> <h4 class="text-center">Tasks Completed</h4></th>
                                <th> <h4 class="text-center"> Outstanding Tasks</h4></th>
                                 <th> <h4 class="text-center"> Totals</h4></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td><a href="{{ url("/admin/progress-report/{$user->id}") }}"> @if ($user->picture)
                                        <img src="{{ asset("{$user->picture}") }}" style="width: 100px; height: 100px;"></a>
                                        @else
                                        <img src="{{ asset("/images/icons/male-icon.png") }}" style="width: 100px; height: 100px;"></a>
                                    @endif
                                    </td>


                                    <td><h5>{{ $user->name }}</h5> </td>
                                    <td><h2 class="text-center">{{ $user->jobs->where('status',1)->count() }} </h2></td>
                                    <td> <h2 class="text-center"> {{ $user->jobs->sum(function($job) { return $job->tasks->where('status',1)->count(); }) }}</h2></td>
                                    <td> <h2 class="text-center"> {{ $user->jobs->sum(function($job) { return $job->tasks->where('status',0)->count(); }) }}</h2></td>
                                     <th> <h4><small>Invoiced: </small><br> £{{ $user->jobs->sum(function($job) {
                    return $job->payments->sum('amount');
                }) }} <br> <small>Settled: </small><br><span style="color: #00B39D">£{{ $user->jobs->sum(function($job) {
                    return $job->payments->where('paid',1)->sum('amount');
                }) }}</span> </h4></th>
                                <tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
        </div>
    </div>
</div>
@endsection
@section('script')

<script>

$(document).ready(function() {

    $(".tasks").click(function() {

        var taskid = $(this).attr('data-key');

        if ($(this).is(":checked")) {
           var status="1";
        } else {
            var status="0";

        }

          $.ajax({
        url: '/tasks/checked',
        type: 'POST',
        headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')  },
        data: {taskid: taskid, status: status},
        success: function(data){
        console.log(data);
        location.reload()

        },
    })
    });

});
</script>
@endsection

resources/views/admin/progress_report_user_job.blade.php
@extends('layouts.frame')

@section('content')
    <style>
        
      /* Style the input field */
      #myInput {
        padding: 20px;
        margin-top: -6px;
        border: 0;
        border-radius: 0;
        background: #f1f1f1;
      }

      #job-search-btn{
          margin-top: 40px;
        background-color: #fff;
        color: #b3b3b3;
        border: solid 0.5px #b3b3b3;
        border-radius: 5px;
            

      }
      h4 h3{
        color: #414860;
        font-weight: bold;
    }
      
      h4 span {
        color: #909090;

      }
      h2{
        color: #00b29c;
        font-weight: bold;
      }
    </style>
    <div class="container-fluid">
        <div class="container">
            <h1>Job for {{ $user->name}} </h1>
            <ol class="breadcrumb"> 
                <li><a href="{{ url('admin') }}">Admin</a></li>
                <li><a href="{{ url('admin/progress-report') }}">Progress Report</a></li>
                <li><a href="{{ url("admin/progress-report/{$user->id}") }}">{{ $user->name}}</a> </li>
                <li>BLSN{{ $job->id}} </li>
            </ol>
        </div>    
        @if($job->tasks->count()<1)
            <div class="container">
                <h3>BLSN{{ $job->id }}</h3>
                <h3 class="text-danger"> This job has no tasks assigned!</h3>
            </div>
        @else
            <div class="container">   
                <div class="row">
                    <div class="col-md-2  col-sm-2 col-xs-12">
                        <a href="{{ url("/admin/my-jobs/view/{$job->id}") }}" style="text-decoration: none;"> 
                            <h3>BLSN{{ $job->id }}</h3>
                        </a>
                        <h2>{{ round((  $job->tasks->where('status',1)->count() / $job->tasks->count() ) * 100) }} % </h2>
                        <p style="color: #00b29b;">Complete</p>
                    </div>
                    <div class="col-md-2 col-sm-2 col-xs-3 text-center">
                        <h3 style="font-size: 1.5em;"> Total </h3>
                        <h1 style="font-size: 2.8em;">{{ $job->tasks->count() }}</h1>
                    </div>

                    <div class="col-md-2  col-sm-2 col-xs-4 text-center">
                        <h3 style="font-size: 1.5em;"> Completed</h3>
                        <h1 style="font-size: 2.8em;">{{ $job->tasks->where('status',1)->count() }}</h1>
                    </div>
                    <div class="col-md-2  col-sm-2 col-xs-5 text-center">
                        <h3 style="font-size: 1.5em;"> Outstanding</h3>
                        <h1 style="font-size: 2.8em;">{{ $job->tasks->where('status',0)->count() }}</h1>
                    </div>
                    <div class="col-md-2  col-sm-2 col-xs-5 text-center">
                        <h3 style="font-size: 1.5em;"> Invoice</h3>
                        <h1 style="font-size: 1.8em;">{{ $job->invoice_no }}</h1>
                    </div>
                    <div class="col-md-2  col-sm-2 col-xs-5 text-right">
                        <h3 style="font-size: 1.5em;" > Cost</h3>
                        <h1 style="font-size: 2.8em;"> £{{ $job->payments->sum('amount') }}</h1>
                    </div>
                </div>
            </div>    
            <div class="container">
                <div class="progress">
                    <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:  {{ (($job->ticked )/$job->tasks->count()) * 100 }}%"></div>
                </div>
            </div>
            @if($job->tasks)   
                <div class="container">
                    <div class="row hidden-xs">
                        <div class="col-md-6 col-sm-7"><h4>Task Name</h4></div>
                        <div class="col-md-3 col-sm-3"><h4>Date of Surveyor Action</h4></div>
                        <div class="col-md-3 col-sm-2"><h4 class="pull-right text-right">Task Completed</h4></div>
                    </div>
                    @foreach($job->tasks as $task)
                        <div class="row">
                            <div class="col-md-6 col-sm-7 col-xs-12"><h4><span>{{ $task->task }}</span></h4></div>
                            <div class="col-md-3 col-sm-3 col-xs-10"><h4> <span>{{ $task->updated_at }}</span></h4></div>
                            <div class="col-md-3 col-sm-2 col-xs-2"><span  class="pull-right">
                                @if($task->status==1) <i class="fa fa-check" aria-hidden="true" style="color: #00B29D; font-size: 30px;"></i> @endif
                            </div>
                        </div>
                        <hr> 
                    @endforeach
                </div>
            @endif             
        @endif 
    </div>
@endsection

@section('script')

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $(".dropdown-menu li").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
    
$(document).ready(function() {

    $(".tasks").click(function() {

        var taskid = $(this).attr('data-key');
        
        if ($(this).is(":checked")) {
           var status="1";
        } else {
            var status="0";
        
        }

          $.ajax({
        url: '/tasks/checked',
        type: 'POST',
        headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')  },
        data: {taskid: taskid, status: status},
        success: function(data){
        console.log(data);
        location.reload()
            
        },
    })  
    });

});
</script>
@endsection